# Generated by Django 3.2.5 on 2021-08-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template_Table',
            fields=[
                ('upload_files', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Templates_Table',
            },
        ),
    ]
