# Generated by Django 3.2.5 on 2021-08-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template_table',
            name='kind',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
