# Generated by Django 3.2.5 on 2021-08-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_alter_template_table_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template_table',
            name='kind',
            field=models.CharField(blank=True, default='cloudstack', max_length=20),
        ),
    ]
