# Generated by Django 3.2.5 on 2021-08-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0004_remove_template_table_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_table',
            name='kind',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
