# Generated by Django 3.2.5 on 2021-08-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0005_template_table_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('upload_files', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Templates',
            },
        ),
        migrations.DeleteModel(
            name='Template_Table',
        ),
    ]
